version: '3.7'

services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
    container_name: 'metricbeat'
    user: root
    network_mode: host
    volumes:
      - ./beats/metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./beats/metricbeat/config/ilm-config.json:/usr/share/metricbeat/ilm-config.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      KIBANA_HOST: ${KIBANA_HOST}
      KIBANA_PORT: ${KIBANA_PORT}
    command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false
    restart: on-failure

networks:
  default:
    name: elastic
    external: false
