metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 5s
  reload.enabled: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

monitoring.enabled: true
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
  username: '${ELASTIC_USERNAME:}'
  password: '${ELASTIC_PASSWORD:}'

setup:
  kibana.host: '${KIBANA_HOST}:${KIBANA_PORT}'
  dashboards.enabled: true

logging.to_files: false
